# Generated by Django 3.0.1 on 2019-12-30 15:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('bot', 'bot'), ('human', 'human')], max_length=128)),
                ('user_telegram_id', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_utterances', to='dialogs.Author')),
                ('human', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='human_utterances', to='dialogs.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Author')),
                ('parent_dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Dialog')),
            ],
        ),
        migrations.CreateModel(
            name='BotUtterance',
            fields=[
                ('utterance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialogs.Utterance')),
            ],
            bases=('dialogs.utterance',),
        ),
        migrations.CreateModel(
            name='HumanUtterance',
            fields=[
                ('utterance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dialogs.Utterance')),
            ],
            bases=('dialogs.utterance',),
        ),
        migrations.CreateModel(
            name='UtteranceHypothesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=256)),
                ('confidence', models.FloatField()),
                ('other_attrs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('parent_utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Utterance')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(max_length=256)),
                ('annotation_dict', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('parent_utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogs.Utterance')),
            ],
        ),
    ]
