# Generated by Django 3.0.1 on 2019-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dp_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
