# Generated by Django 3.0.1 on 2019-12-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_author_dp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
