# Generated by Django 3.0.1 on 2020-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0004_dialog_dp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utterance',
            name='text',
            field=models.CharField(max_length=2064),
        ),
        migrations.AlterField(
            model_name='utterancehypothesis',
            name='text',
            field=models.CharField(max_length=2064),
        ),
    ]
