# Generated by Django 3.0.1 on 2020-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0006_utterance_active_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterance',
            name='version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
