# Generated by Django 3.0.1 on 2020-04-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0007_utterance_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='conversation_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
